require 'pry'
require 'open-uri'
require 'json'
require 'httparty'

require_relative 'your_favorite_artist/version'
require_relative 'your_favorite_artist/CLI'
require_relative 'your_favorite_artist/API'
require_relative 'your_favorite_artist/artist'
require_relative 'your_favorite_artist/album'